# Archivo: src/main/resources/application.yml
server:
  port: 8888

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fransasdsa/examen2.git
          default-label: main
          search-paths:
            - config-repo
  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
