server:
  port: 8761

spring:
  application:
    name: ms-eureka-server
  profiles:
    active: default

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
