# Archivo: src/main/resources/application.yml
server:
  port: 8085

spring:
  application:
    name: ms-notification-service
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/ms-notification-service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.your-email.com
    port: 587
    username: your_email_username
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
